import { PDFDocument, PDFFont, StandardFonts, rgb } from "pdf-lib";
import { questions } from "../data/catalog";
import { translations } from "../data/translations";
import type { AiOutputs, Answers, Question, ScoreResult } from "../types";

export async function downloadReport(answers: Answers, aiOutputs: AiOutputs, scoreResult: ScoreResult) {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const state = { page: pdf.addPage([612, 792]), y: 744, regular, bold };

  write(pdf, state, "MSI360 Risk Report", 20, bold);
  write(pdf, state, `Date of this report: ${new Date().toLocaleDateString("en-CA")}`, 10, regular);
  gap(state, 14);
  paragraph(
    pdf,
    state,
    "This report was generated by the MSI360 prototype. It is based on one person's responses and is intended to support conversations about musculoskeletal injury risk.",
    11
  );

  section(pdf, state, "Overview Of Results");
  write(pdf, state, `Composite score: ${formatScore(scoreResult.composite_score)}`, 11, bold);
  write(pdf, state, `Physical score: ${formatScore(scoreResult.grouped_scores.physical)}`, 10, regular);
  write(pdf, state, `Environmental score: ${formatScore(scoreResult.grouped_scores.environmental)}`, 10, regular);
  write(pdf, state, "Organizational/work-design context: included in answers, not scored.", 10, regular);

  section(pdf, state, "Detailed Questions And Answers");
  questions.forEach((question) => {
    const answer = answers[question.question_id];
    if (!answer) return;
    paragraph(pdf, state, getQuestionLabel(question), 10, bold);
    formatAnswer(question, answer.value, aiOutputs[question.question_id]).forEach((line) => paragraph(pdf, state, line, 9, regular));
    gap(state, 5);
  });

  section(pdf, state, "Prototype Notes");
  paragraph(pdf, state, "Question grading mappings are placeholders and can be replaced in the client catalog.", 9, regular);

  const bytes = await pdf.save();
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  const blob = new Blob([buffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "MSI360-risk-report.pdf";
  link.click();
  URL.revokeObjectURL(url);
}

function formatAnswer(question: Question, value: unknown, aiOutput = undefined as AiOutputs[string] | undefined): string[] {
  if (question.type === "text") {
    const lines = [`Answer: ${String(value || "")}`];
    if (aiOutput?.normalized_answer_en && aiOutput.normalized_answer_en !== value) lines.push(`English interpretation: ${aiOutput.normalized_answer_en}`);
    return lines;
  }

  if (question.options) {
    const values = Array.isArray(value) ? value : typeof value === "string" ? [value] : [];
    return [`Answer: ${values.map((optionId) => getOptionLabel(question.question_id, optionId)).join("; ")}`];
  }

  if (!value || typeof value !== "object" || Array.isArray(value)) return ["Answer: No answer"];

  return Object.entries(value as Record<string, string | string[]>).map(([groupId, groupValue]) => {
    const values = Array.isArray(groupValue) ? groupValue : [groupValue];
    return `${getGroupLabel(question.question_id, groupId)}: ${values.map((optionId) => getOptionLabel(question.question_id, optionId, groupId)).join("; ")}`;
  });
}

function getQuestionLabel(question: Question) {
  return translations.en.questions[question.question_id]?.label || question.question_id;
}

function getGroupLabel(questionId: string, groupId: string) {
  return translations.en.questions[questionId]?.groups?.[groupId]?.label || groupId;
}

function getOptionLabel(questionId: string, optionId: string, groupId?: string) {
  if (groupId) return translations.en.questions[questionId]?.groups?.[groupId]?.options[optionId] || optionId;
  return translations.en.questions[questionId]?.options?.[optionId] || optionId;
}

function section(pdf: PDFDocument, state: PdfState, title: string) {
  gap(state, 16);
  write(pdf, state, title, 14, state.bold);
  gap(state, 5);
}

function paragraph(pdf: PDFDocument, state: PdfState, text: string, size: number, font = state.regular) {
  wrap(text, font, size, 500).forEach((line) => write(pdf, state, line, size, font));
}

function write(pdf: PDFDocument, state: PdfState, text: string, size: number, font: typeof state.regular) {
  if (state.y < 56) {
    state.page = pdf.addPage([612, 792]);
    state.y = 744;
  }
  state.page.drawText(text, { x: 56, y: state.y, size, font, color: rgb(0.08, 0.08, 0.08) });
  state.y -= size + 5;
}

function gap(state: PdfState, amount: number) {
  state.y -= amount;
}

function wrap(text: string, font: PDFFont, size: number, maxWidth: number) {
  const words = String(text).split(/\s+/);
  const lines: string[] = [];
  let line = "";
  words.forEach((word) => {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) line = candidate;
    else {
      if (line) lines.push(line);
      line = word;
    }
  });
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

function formatScore(score: number | null) {
  return typeof score === "number" ? `${score}/4` : "N/A";
}

interface PdfState {
  page: ReturnType<PDFDocument["addPage"]>;
  y: number;
  regular: Awaited<ReturnType<PDFDocument["embedFont"]>>;
  bold: Awaited<ReturnType<PDFDocument["embedFont"]>>;
}
